import React, { useEffect, useState } from 'react';
import { Configuration, OpenAIApi } from "openai";

function Generate(props) {

    const configuration = new Configuration({
        apiKey: process.env.REACT_APP_OPENAI_API_KEY,
    });
    const openai = new OpenAIApi(configuration);

    const [prompt, setPrompt] = useState("");
    const [image, setImage] = useState("");

    const generateImage = async () => {

        const response = await openai.createImage({
            prompt: prompt,
            n: parseInt(1),
            size: "512x512",
        });
        setImage(response.data.data[0].url);
        console.log(response.data.data[0].url);
    }

    useEffect(() => {
        generateImage();
    }, []);

    return (
        // <div>
        //     {image && <img src={image} alt="Document generated by the AI" />}
        //     <h1>Generate an Picture</h1>
        //     Prompt:<input type='text' onChange={(e) => setPrompt(e.target.value)} />
        //     Nbre:<input type='number' onChange={(e) => setSize(e.target.value)} />
        //     <button onClick={generateImage}>Generate</button>
        // </div>

        <>

            <div className="flex min-h-screen flex-col justify-center bg-[#0a1120] bg-[url('https://mini.codingcodax.dev/images/dark-beams.jpg')] bg-[length:86.125rem] bg-bottom bg-no-repeat p-4">
                <div className="inset-0 bg-[url('https:https://snippets.alexandru.so///mini.codingcodax.dev/images/dark-grid.svg')]"></div>
                {image && <img className='mx-auto my-6' src={image} alt="Document generated by the AI" />}
                <span className='text-2xl text-white mb-4 mx-auto'>"White everything that comes to your mind. My IA will generate your NFT picture"</span>
                <div className="mx-auto w-screen-sm">

                    <div className="relative flex h-10 w-full flex-row-reverse overflow-clip rounded-lg">
                        <input onChange={(e) => setPrompt(e.target.value)} className="peer w-full rounded-r-lg border border-slate-400 px-2 text-slate-900 placeholder-slate-400 transition-colors duration-300 focus:border-sky-400 focus:outline-none" type="text" name="domain" id="domain" placeholder="whatever you want" />
                        <button
                            type="button"
                            className="border border-pink-600 bg-pink-600 text-white px-2 rounded-tl-md rounded-bl-md transition duration-500 ease select-none hover:bg-pink-800 focus:outline-none focus:shadow-outline"
                            onClick={generateImage}
                        >
                            Generate
                        </button>
                    </div>
                </div>
            </div>
        </>
    );
}

export default Generate;